#!/usr/bin/env bash
# server -01 login

eval $("ssh-agent")

ssh-add ~/.ssh/school

ssh ubuntu@54.236.119.41 

ssh ubuntu@54.236.119.41 << EOF
  scp /root/alx-system_engineering-devops/0x0B-ssh/README.md /root/
EOF
